task/error-handling
tasknotfound/Shared.Abstract pull request #3
Opened 2024-04-30 13:31 UTC by makeitvsolo

Added:
- Result API
- Optional API

2024-05-04 12:49 UTC, shishnk requested changes

2024-05-04 12:49 UTC, shishnk commented on Shared.Abstract.UnitTests/ErrorHandling/Optionals/OptionalTests.cs
> +        }
it's best to stick to the one-line style with => + use FluentAssertions with syntax example
`_optional.IsPresent.Should().Be(true)`
Also use different naming convention for test methods -> [click](https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices)
```
The name of your test should consist of three parts:

    The name of the method being tested.
    The scenario under which it's being tested.
    The expected behavior when the scenario is invoked.
```

2024-05-04 12:49 UTC, shishnk commented on Shared.Abstract.UnitTests/ErrorHandling/Optionals/OptionalTests.cs
> +using TaskNotFound.Shared.Abstract.ErrorHandling.Exceptions;
Namespace does not correspond to file location, must be: `'Shared.Abstract.UnitTests.ErrorHandling.Optionals'` by ReSharper.
Also this problem in another files.

2024-05-04 12:49 UTC, shishnk commented on Shared.Abstract.UnitTests/ErrorHandling/Optionals/OptionalTests.cs
> +        private Optional<TestValue> _optional;
Fields can be made readonly

2024-05-04 12:49 UTC, shishnk commented on Shared.Abstract.UnitTests/ErrorHandling/Optionals/OptionalTests.cs
> +            _value = new TestValue();
Can be simply with `_value = new();`

2024-05-04 12:49 UTC, shishnk commented on Shared.Abstract.UnitTests/ErrorHandling/Optionals/OptionalTests.cs
> +            var expected = 1;
Convert this variable to constant (example: `const int expected = 0;`)

2024-05-04 12:49 UTC, shishnk commented on Shared.Abstract.UnitTests/ErrorHandling/Results/ResultTests.cs
> +        private Result<TestValue, TestError> _result;
Fields can be readonly.

2024-05-04 12:49 UTC, shishnk commented on Shared.Abstract.UnitTests/ErrorHandling/Results/ResultTests.cs
> +            _value = new TestValue();
Can be simply with `_value = new();`

2024-05-04 12:49 UTC, shishnk commented on Shared.Abstract.UnitTests/ErrorHandling/Results/ResultTests.cs
> +        private Result<TestValue, TestError> _result;
Fields can be readonly.

2024-05-04 12:49 UTC, shishnk commented on Shared.Abstract.UnitTests/ErrorHandling/Results/ResultTests.cs
> +            _error = new TestError();
Can be simply with `_error = new();`

2024-05-04 12:49 UTC, shishnk commented on Shared.Abstract/ErrorHandling/Optionals/Empty.cs
> +    }
Empty constructor is redundant. The compiler generates the same by default.

2024-05-04 13:12 UTC, makeitvsolo commented on Shared.Abstract.UnitTests/ErrorHandling/Optionals/OptionalTests.cs
> +using TaskNotFound.Shared.Abstract.ErrorHandling.Exceptions;
Wtf is `Shared.Abstract`?
This library belongs to the project `TaskNotFound`.

2024-05-04 13:14 UTC, makeitvsolo commented on Shared.Abstract.UnitTests/ErrorHandling/Optionals/OptionalTests.cs
> +        private Optional<TestValue> _optional;
I wouldn't follow the rules in test projects.

2024-05-04 13:17 UTC, makeitvsolo commented on Shared.Abstract/ErrorHandling/Optionals/Empty.cs
> +    }
Default construct is public, but i want internal constructor

2024-05-04 13:35 UTC, makeitvsolo commented on Shared.Abstract.UnitTests/ErrorHandling/Optionals/OptionalTests.cs
> +        private Optional<TestValue> _optional;
> I wouldn't follow the rules in test projects.

I found out that I don't write in java, so no problem making them readonly

2024-05-04 13:40 UTC, shishnk commented on Shared.Abstract/ErrorHandling/Optionals/Empty.cs
> +    }
Is truth.

2024-05-04 13:43 UTC, shishnk commented on Shared.Abstract.UnitTests/ErrorHandling/Optionals/OptionalTests.cs
> +using TaskNotFound.Shared.Abstract.ErrorHandling.Exceptions;
Will be fixed by ignoring the warning.

2024-05-05 07:08 UTC, shishnk approved these changes

2024-05-05 07:09 UTC, merged